- name: Copy tar archive with Logstash
  copy:
    src: "logstash-8.4.3-linux-x86_64.tar.gz"
    dest: "/home/ubuntu/logstash-8.4.3-linux-x86_64.tar.gz"
    mode: 0700
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Extract Logstash in the installation directory
  shell: tar -xzf logstash-8.4.3-linux-x86_64.tar.gz

- name: Copy test config with pipeline
  copy:
    src: "first-pipeline.conf"
    dest: "/home/ubuntu/logstash-8.4.3/first-pipeline.conf"
    mode: 0777
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Copy config file
  copy:
    src: "logstash.yml"
    dest: "/home/ubuntu/logstash-8.4.3/config/logstash.yml"
    mode: 0777
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Copy unit file to start Logstash as daemon
  become: true
  copy:
    src: "logstash.service"
    dest: "/etc/systemd/system/logstash.service"
    mode: 0644
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Daemon-reload to apply changes and start Logstash
  become: true
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: logstash
