---
- hosts: elk
  roles:
    - elasticsearch_role
    - kibana_role
    - logstash_role

- hosts: proxy_nginx
  roles:
    - jenkins_role
    - nginx_role
    - letsencrypt_role
    - filebeat_role
  become: true

- hosts: app_level_balancer
  roles:
    - jenkins_role
    - app_level_balancer_role
    - filebeat_role
  become: true

- hosts: sentiment_estimators
  roles:
    - jenkins_role
    - sentiment_analysis_model_role
    - filebeat_role
  become: true
