- name: Creates new user for remote access from Jenkins
  shell: useradd -m jenkins

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/jenkins/.ssh
    state: directory
    mode: '0700'

- name: Copy file with public ssh key for the jenkins user to the remote host
  copy:
    src: "authorized_keys"
    dest: "/home/jenkins/.ssh/authorized_keys"
    mode: 0700
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Recursively change ownership of the .ssh directory
  ansible.builtin.file:
    path: /home/jenkins/.ssh
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins

- name: Restart ssh daemon
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: sshd
