- name: Copy tar archive with Filebeat
  copy:
    src: "filebeat-8.4.3-linux-x86_64.tar.gz"
    dest: "/home/ubuntu/filebeat-8.4.3-linux-x86_64.tar.gz"
    mode: 0700
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Extract Filebeat in the installation directory
  shell: tar -xzf filebeat-8.4.3-linux-x86_64.tar.gz

- name: Copy ca_cert to the Filebeat node
  copy:
    src: /tmp/http_ca.crt
    dest: /home/ubuntu/filebeat-8.4.3-linux-x86_64/http_ca.crt
    mode: 0755
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Upload Filebeat config
  copy:
    src: filebeat.{{ inventory_hostname }}.yml
    dest: /home/ubuntu/filebeat-8.4.3-linux-x86_64/filebeat.yml
    mode: 0755
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Copy unit file to start Filebeat as daemon
  become: true
  copy:
    src: "filebeat.service"
    dest: "/etc/systemd/system/filebeat.service"
    mode: 0644
  register: file_uploaded
  until: file_uploaded is succeeded

- name: Daemon-reload to apply changes and start Filebeat
  become: true
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: filebeat
